import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, json } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(), deadlineScheduleTaskUid: varchar("deadlineScheduleTaskUid", { length: 65 }),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

export const companies = mysqlTable("companies", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 255 }).notNull(), address: text("address"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const customers = mysqlTable("customers", { id: int("id").autoincrement().primaryKey(), companyId: int("companyId").notNull(), contactName: varchar("contactName", { length: 255 }), email: varchar("email", { length: 320 }), phone: varchar("phone", { length: 64 }), address: text("address"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const rfqs = mysqlTable("rfqs", { id: int("id").autoincrement().primaryKey(), rfqNumber: varchar("rfqNumber", { length: 64 }).notNull().unique(), customerId: int("customerId").notNull(), title: varchar("title", { length: 255 }).notNull(), status: mysqlEnum("status", ["NEW", "PROCESSING", "REVIEW_REQUIRED", "WAITING_FOR_INFORMATION", "READY_FOR_QUOTE", "QUOTED", "WON", "LOST"]).default("NEW").notNull(), priority: mysqlEnum("priority", ["LOW", "MEDIUM", "HIGH"]).default("MEDIUM").notNull(), risk: mysqlEnum("risk", ["LOW", "MEDIUM", "HIGH"]).default("LOW").notNull(), receivedAt: timestamp("receivedAt").defaultNow().notNull(), deadline: timestamp("deadline"), currency: varchar("currency", { length: 8 }).default("USD").notNull(), deliveryLocation: text("deliveryLocation"), paymentTerms: varchar("paymentTerms", { length: 128 }), incoterms: varchar("incoterms", { length: 64 }), estimatedValue: decimal("estimatedValue", { precision: 14, scale: 2 }), assignedUserId: int("assignedUserId"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const rfqDocuments = mysqlTable("rfq_documents", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), fileKey: varchar("fileKey", { length: 512 }).notNull(), fileUrl: varchar("fileUrl", { length: 1024 }).notNull(), fileName: varchar("fileName", { length: 255 }).notNull(), mimeType: varchar("mimeType", { length: 128 }), sizeBytes: int("sizeBytes"), documentType: varchar("documentType", { length: 64 }).default("rfq"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const rfqItems = mysqlTable("rfq_items", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), sku: varchar("sku", { length: 128 }), productName: varchar("productName", { length: 255 }).notNull(), description: text("description"), quantity: decimal("quantity", { precision: 14, scale: 3 }), unit: varchar("unit", { length: 32 }), dimensions: varchar("dimensions", { length: 255 }), material: varchar("material", { length: 255 }), grade: varchar("grade", { length: 128 }), specifications: text("specifications"), certifications: text("certifications"), deliveryRequirements: text("deliveryRequirements"), specialRequirements: text("specialRequirements"), confidence: decimal("confidence", { precision: 5, scale: 2 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const rfqRequirements = mysqlTable("rfq_requirements", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), label: varchar("label", { length: 255 }).notNull(), status: mysqlEnum("status", ["approved", "missing", "exception"]).default("missing").notNull(), note: text("note"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const assignments = mysqlTable("assignments", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), assigneeId: int("assigneeId").notNull(), role: mysqlEnum("role", ["sales", "engineering", "pricing", "manager"]).notNull(), status: mysqlEnum("status", ["open", "completed", "overdue"]).default("open").notNull(), dueAt: timestamp("dueAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const clarifications = mysqlTable("clarifications", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), subject: varchar("subject", { length: 255 }).notNull(), body: text("body").notNull(), status: mysqlEnum("status", ["draft", "sent", "resolved", "cancelled"]).default("draft").notNull(), assigneeId: int("assigneeId"), sentAt: timestamp("sentAt"), resolvedAt: timestamp("resolvedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const quotes = mysqlTable("quotes", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), quoteNumber: varchar("quoteNumber", { length: 64 }).notNull().unique(), status: mysqlEnum("status", ["draft", "ready", "sent", "won", "lost"]).default("draft").notNull(), currency: varchar("currency", { length: 8 }).default("USD").notNull(), discount: decimal("discount", { precision: 14, scale: 2 }).default("0"), tax: decimal("tax", { precision: 14, scale: 2 }).default("0"), shipping: decimal("shipping", { precision: 14, scale: 2 }).default("0"), subtotal: decimal("subtotal", { precision: 14, scale: 2 }).default("0"), grandTotal: decimal("grandTotal", { precision: 14, scale: 2 }).default("0"), leadTime: varchar("leadTime", { length: 128 }), validityDays: int("validityDays"), paymentTerms: varchar("paymentTerms", { length: 128 }), notes: text("notes"), documentKey: varchar("documentKey", { length: 512 }), documentUrl: varchar("documentUrl", { length: 1024 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const quoteItems = mysqlTable("quote_items", { id: int("id").autoincrement().primaryKey(), quoteId: int("quoteId").notNull(), rfqItemId: int("rfqItemId"), description: text("description").notNull(), quantity: decimal("quantity", { precision: 14, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 14, scale: 2 }).notNull(), lineTotal: decimal("lineTotal", { precision: 14, scale: 2 }).notNull() });
export const tasks = mysqlTable("tasks", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), assigneeId: int("assigneeId"), label: varchar("label", { length: 255 }).notNull(), status: mysqlEnum("status", ["open", "completed", "overdue"]).default("open").notNull(), dueAt: timestamp("dueAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId"), rfqId: int("rfqId"), type: varchar("type", { length: 64 }).notNull(), title: varchar("title", { length: 255 }).notNull(), body: text("body").notNull(), readAt: timestamp("readAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const activity = mysqlTable("activity", { id: int("id").autoincrement().primaryKey(), rfqId: int("rfqId").notNull(), actorId: int("actorId"), action: varchar("action", { length: 255 }).notNull(), metadata: json("metadata"), createdAt: timestamp("createdAt").defaultNow().notNull() });
