import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CalendarClock, ChevronRight, Clock3, MoreHorizontal, Plus, Sparkles, Target, TrendingUp, UploadCloud } from "lucide-react";
import { useMemo } from "react";
import { Link } from "wouter";

type DashboardRow = { id: string; customer: string; product: string; received: string; status: string; owner: string; value: string; priority: string; stage: string };

const fallbackRfqs: DashboardRow[] = [
  { id: "RFQ-1048", customer: "Nordic Motion Systems", product: "Servo motor assembly", received: "Today, 08:42", status: "Review required", owner: "MK", value: "$48,600", priority: "High", stage: "2h 18m" },
  { id: "RFQ-1047", customer: "Axion Process Controls", product: "316L valve manifold", received: "Today, 07:15", status: "Waiting on customer", owner: "AR", value: "$21,900", priority: "Medium", stage: "5h 04m" },
  { id: "RFQ-1046", customer: "HelioFab Industries", product: "Laser-cut enclosure", received: "Yesterday", status: "Quote ready", owner: "PS", value: "$86,240", priority: "High", stage: "1d 06h" },
  { id: "RFQ-1045", customer: "Westline Robotics", product: "Precision shaft kit", received: "Yesterday", status: "Pricing", owner: "JT", value: "$12,780", priority: "Low", stage: "1d 11h" },
  { id: "RFQ-1044", customer: "Arcwell Energy", product: "Custom busbar set", received: "Aug 31, 14:20", status: "Quoted", owner: "MK", value: "$34,500", priority: "Medium", stage: "3d 02h" },
];

const statusLabels: Record<string, string> = { NEW: "New", PROCESSING: "In processing", REVIEW_REQUIRED: "Review required", WAITING_FOR_INFORMATION: "Waiting on customer", READY_FOR_QUOTE: "Quote ready", QUOTED: "Quoted", WON: "Won", LOST: "Lost" };
const statusTone: Record<string, string> = { "Review required": "bg-amber-50 text-amber-700", "Waiting on customer": "bg-violet-50 text-violet-700", "Quote ready": "bg-emerald-50 text-emerald-700", Pricing: "bg-sky-50 text-sky-700", Quoted: "bg-slate-100 text-slate-600", New: "bg-blue-50 text-blue-700", "In processing": "bg-sky-50 text-sky-700", Won: "bg-emerald-50 text-emerald-700", Lost: "bg-rose-50 text-rose-700" };

function formatCurrency(value: string | number | null | undefined) {
  if (value === null || value === undefined || value === "") return "—";
  const amount = Number(value);
  return Number.isFinite(amount) ? `$${amount.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : String(value);
}

function Metric({ label, value, delta, tone = "blue", note }: { label: string; value: string; delta: string; tone?: string; note: string }) {
  const colors: Record<string, string> = { blue: "bg-[#eaf0f8] text-[#315477]", green: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", violet: "bg-violet-50 text-violet-700" };
  return <Card className="border-0 shadow-[0_10px_30px_rgba(28,49,76,0.06)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-[28px] font-semibold tracking-[-0.04em] text-[#152238]">{value}</p></div><span className={`rounded-lg px-2 py-1 text-[11px] font-semibold ${colors[tone]}`}>{delta}</span></div><p className="mt-3 text-[11px] text-slate-400">{note}</p></CardContent></Card>;
}

export default function Home() {
  const { data: persistedRfqs, isLoading } = trpc.rfq.list.useQuery(undefined, { retry: false });
  const liveRows = useMemo<DashboardRow[]>(() => (persistedRfqs ?? []).map(({ rfq, company }) => ({
    id: rfq.rfqNumber,
    customer: company?.name ?? "Unassigned customer",
    product: rfq.title,
    received: new Date(rfq.receivedAt).toLocaleDateString(undefined, { month: "short", day: "2-digit" }),
    status: statusLabels[rfq.status] ?? rfq.status,
    owner: rfq.assignedUserId ? "AS" : "—",
    value: formatCurrency(rfq.estimatedValue),
    priority: rfq.priority.charAt(0) + rfq.priority.slice(1).toLowerCase(),
    stage: rfq.deadline ? new Date(rfq.deadline).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "No deadline",
  })), [persistedRfqs]);
  const usingFallback = persistedRfqs === undefined;
  const rfqs = usingFallback ? fallbackRfqs : liveRows;
  const openCount = usingFallback ? 28 : liveRows.filter((row) => !["Quoted", "Won", "Lost"].includes(row.status)).length;
  const quoteReadyCount = usingFallback ? 4 : liveRows.filter((row) => row.status === "Quote ready").length;
  const quotedValue = usingFallback ? "$184.2k" : formatCurrency(liveRows.reduce((sum, row) => sum + (Number(row.value.replace(/[$,]/g, "")) || 0), 0));
  const pipelineRows = usingFallback ? [["New", "05", "18%", "#829fc1"], ["In review", "08", "29%", "#52759f"], ["Waiting", "06", "21%", "#9e8ac6"], ["Pricing", "05", "17%", "#d5a860"], ["Ready", String(quoteReadyCount).padStart(2, "0"), "15%", "#79b28e"]] : [["New", String(liveRows.filter((row) => row.status === "New").length).padStart(2, "0"), "", "#829fc1"], ["In review", String(liveRows.filter((row) => row.status === "In processing" || row.status === "Review required").length).padStart(2, "0"), "", "#52759f"], ["Waiting", String(liveRows.filter((row) => row.status === "Waiting on customer").length).padStart(2, "0"), "", "#9e8ac6"], ["Pricing", "00", "", "#d5a860"], ["Ready", String(quoteReadyCount).padStart(2, "0"), "", "#79b28e"]];

  return <div className="space-y-7 animate-in fade-in-0 duration-500"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#6885a5]"><Sparkles className="h-3.5 w-3.5" /> Monday, September 04, 2026</div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-[#152238] sm:text-4xl">Good morning, Prathik.</h1><p className="mt-2 text-sm text-slate-500">Here’s the pulse of your quotation operation.</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-xl border-slate-200 bg-white text-slate-600"><CalendarClock className="mr-2 h-4 w-4" />This week</Button><Link href="/inbox"><Button className="rounded-xl bg-[#152238] px-4 hover:bg-[#223653]"><Plus className="mr-2 h-4 w-4" />New RFQ</Button></Link></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Open RFQs" value={String(openCount).padStart(2, "0")} delta={liveRows.length ? "Live" : "+12.5%"} note={usingFallback ? "vs. previous 30 days" : "from persisted workspace records"} /><Metric label="Needs attention" value={usingFallback ? "07" : String(liveRows.filter((row) => row.status.includes("Review") || row.status.includes("Waiting")).length).padStart(2, "0")} delta={usingFallback ? "3 urgent" : "Live"} tone="amber" note="review or clarification work" /><Metric label="Quoted value" value={quotedValue} delta={usingFallback ? "+8.4%" : "Live"} tone="green" note={usingFallback ? "across 9 active quotes" : "across persisted RFQs"} /><Metric label="Avg. time to quote" value="18.6h" delta="−14.2%" tone="violet" note="target is under 24h" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.45fr_0.8fr]"><Card className="border-0 shadow-[0_10px_30px_rgba(28,49,76,0.06)]"><CardHeader className="flex flex-row items-start justify-between space-y-0 pb-3"><div><CardTitle className="text-base font-semibold text-[#152238]">Pipeline health</CardTitle><p className="mt-1 text-xs text-slate-400">{usingFallback ? "28 open requests across your active workflow" : `${liveRows.length} persisted requests in your workspace`}</p></div><Button variant="ghost" size="icon" className="text-slate-400"><MoreHorizontal className="h-4 w-4" /></Button></CardHeader><CardContent><div className="flex h-3 overflow-hidden rounded-full bg-slate-100"><div className="w-[18%] bg-[#829fc1]" /><div className="w-[29%] bg-[#52759f]" /><div className="w-[21%] bg-[#9e8ac6]" /><div className="w-[17%] bg-[#d5a860]" /><div className="w-[15%] bg-[#79b28e]" /></div><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-5">{pipelineRows.map(([label, value, pct, color]) => <div key={label} className="space-y-1"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: color }} /><span className="text-xs text-slate-500">{label}</span></div><p className="text-xl font-semibold text-[#152238]">{value}</p><p className="text-[11px] text-slate-400">{pct} of total</p></div>)}</div></CardContent></Card><Card className="border-0 bg-[#152238] text-white shadow-[0_10px_30px_rgba(28,49,76,0.14)]"><CardHeader className="pb-2"><div className="flex items-center justify-between"><CardTitle className="text-base font-semibold">Priority queue</CardTitle><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-[#b9d4f2]">{isLoading ? "Syncing" : "Live"}</span></div><p className="text-xs text-slate-400">Work most likely to move revenue today.</p></CardHeader><CardContent className="space-y-4 pt-3">{rfqs.length === 0 && !isLoading ? <div className="rounded-xl border border-white/10 p-4 text-xs text-slate-400">No priority work in the current workspace.</div> : rfqs.slice(0, 3).map((item, index) => <Link href={`/rfq/${item.id}`} key={item.id}><div className="group flex items-center gap-3 rounded-xl border border-white/10 p-3 transition hover:bg-white/5"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-amber-400" : index === 1 ? "bg-emerald-400" : "bg-violet-400"}`} /><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-white">{item.id}</p><p className="mt-0.5 truncate text-xs text-slate-400">{item.status}</p></div><div className="text-right"><p className="text-[11px] font-medium text-slate-300">{item.stage}</p><ChevronRight className="ml-auto mt-1 h-3.5 w-3.5 text-slate-500 transition group-hover:translate-x-0.5" /></div></div></Link>)}</CardContent></Card></div>
    <Card className="border-0 shadow-[0_10px_30px_rgba(28,49,76,0.06)]"><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle className="text-base font-semibold text-[#152238]">Recent RFQs</CardTitle><p className="mt-1 text-xs text-slate-400">{usingFallback ? "The latest requests moving through the workspace." : "Live records from the RFQ workspace."}</p></div><Link href="/inbox"><Button variant="ghost" className="text-xs font-semibold text-[#315477]">View inbox <ArrowUpRight className="ml-1.5 h-3.5 w-3.5" /></Button></Link></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-y border-slate-100 text-[10px] uppercase tracking-[0.13em] text-slate-400"><th className="px-6 py-3 font-semibold">RFQ / customer</th><th className="px-4 py-3 font-semibold">Status</th><th className="px-4 py-3 font-semibold">Owner</th><th className="px-4 py-3 font-semibold">Est. value</th><th className="px-4 py-3 font-semibold">Stage time</th><th /></tr></thead><tbody>{rfqs.map((rfq) => <tr key={rfq.id} className="group border-b border-slate-50 transition hover:bg-slate-50/80"><td className="px-6 py-4"><Link href={`/rfq/${rfq.id}`}><div><p className="text-xs font-semibold text-[#315477]">{rfq.id}</p><p className="mt-1 text-sm font-medium text-[#152238]">{rfq.customer}</p><p className="mt-0.5 text-xs text-slate-400">{rfq.product} · {rfq.received}</p></div></Link></td><td className="px-4 py-4"><Badge className={`rounded-full border-0 px-2.5 py-1 text-[10px] font-semibold ${statusTone[rfq.status] ?? "bg-slate-100 text-slate-600"}`}>{rfq.status}</Badge></td><td className="px-4 py-4"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#eaf0f8] text-[10px] font-semibold text-[#315477]">{rfq.owner}</span><span className="text-xs text-slate-500">{rfq.priority}</span></div></td><td className="px-4 py-4 text-sm font-semibold text-[#152238]">{rfq.value}</td><td className="px-4 py-4 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5 text-slate-400" />{rfq.stage}</span></td><td className="px-5 py-4"><ChevronRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#315477]" /></td></tr>)}</tbody></table>{!isLoading && !usingFallback && rfqs.length === 0 && <div className="p-12 text-center"><p className="text-sm font-semibold text-[#152238]">No persisted RFQs yet</p><p className="mt-1 text-xs text-slate-500">Create a request from the inbox to start your quotation pipeline.</p><Link href="/inbox"><Button variant="outline" size="sm" className="mt-4 rounded-xl border-slate-200">Open RFQ inbox</Button></Link></div>}</div></CardContent></Card>
    <div className="grid gap-5 md:grid-cols-3"><Card className="border-0 bg-[#edf4fb] shadow-none"><CardContent className="p-5"><UploadCloud className="h-5 w-5 text-[#52759f]" /><p className="mt-4 text-sm font-semibold text-[#152238]">Drop in a new RFQ</p><p className="mt-1 text-xs leading-5 text-slate-500">PDFs, DOCX, drawings, and spec packs are all welcome.</p><Link href="/inbox"><Button variant="link" className="mt-2 h-auto px-0 text-xs text-[#315477]">Open upload inbox <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Button></Link></CardContent></Card><Card className="border-0 bg-[#f5f1fb] shadow-none"><CardContent className="p-5"><Target className="h-5 w-5 text-[#806ca9]" /><p className="mt-4 text-sm font-semibold text-[#152238]">Quote readiness</p><p className="mt-1 text-xs leading-5 text-slate-500">74% of active requests have complete commercial terms.</p><div className="mt-4 h-1.5 rounded-full bg-white"><div className="h-1.5 w-[74%] rounded-full bg-[#806ca9]" /></div></CardContent></Card><Card className="border-0 bg-[#eef8f1] shadow-none"><CardContent className="p-5"><TrendingUp className="h-5 w-5 text-[#5b9a71]" /><p className="mt-4 text-sm font-semibold text-[#152238]">Win rate trending up</p><p className="mt-1 text-xs leading-5 text-slate-500">42% this month, 6 pts higher than last month.</p><Button variant="link" className="mt-2 h-auto px-0 text-xs text-[#43855a]" onClick={() => window.location.assign("/analytics")}>Review analytics <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Button></CardContent></Card></div>
  </div>;
}
